### ISSUE TITLE
Problems running on a simulator

### ISSUE THREAD

**Issue by piotr-j** [spilgames/spil-ios-sdk#2]
Perhaps my need to run on a simulator is unusual, but is the sdk supposed to run on it out of the box? Ive had quite a bit of trouble making it run, had to download and add all frameworks, and compile without `HookBridge::UnitySendMessage` as the flags required to make it work dont seem to work on a simulator.

**Comment by FrankSpil** [comment]
Hi piotr-j,

The SDK supports simulators out of the box without any modifications, just follow the following steps:
- Download one of the releases for example: https://github.com/spilgames/spil-ios-sdk/releases/download/v2.0.3/Spil.framework.zip and unzip it.
- Copy Spil.framework to the root of your project. (should be located in the directory that contains the .xcodeproj file.)
- Add a new 'Run Script' phase - ON TOP - of the Build Phases tab using the following Shell command and build the project: /usr/bin/python Spil.framework/setup.py $(PROJECT_NAME) 

OR: It is also possible to run the setup script from the terminal using: 'python Spil.framework/setup.py <ProjectName>'

Hopefully this answers your question.

**Comment by piotr-j** [comment]
Hi Frank

That was very smooth and works as advertised. Ive noticed the script before, but Ive used it incorrectly. This info really should end up in the readme!

Thanks!

**Comment by FrankSpil** [comment]
No problem, glad that it worked! You're right it's a bit hidden in the documentation at this moment. I'll move it also to the Readme.me file so that it's right there on github.
