### ISSUE TITLE
Issue with GameDataEvents delegation

### ISSUE THREAD

**Issue by piotr-j** [spilgames/spil-ios-sdk#3]
There seems to be an issue with GameDataAvailable/Error event delegation.
[GameDataController](https://github.com/spilgames/spil-ios-sdk/blob/master/Spil/GameData/GameDataController.m#L62) sends "gameDataAvailable" event but [Spil](https://github.com/spilgames/spil-ios-sdk/blob/master/Spil/Spil.m#L146) checks for "spilGameDataAvailable". This results in the delegate methods to never be called.

**Comment by FrankSpil** [comment]
Thank you for reporting this issue, it's fixed in the next release.
