### ISSUE TITLE
Wallet and Inventory missing documentation for some parameters

### ISSUE THREAD

**Issue by iCarambaa** [spilgames/spil-ios-sdk#7]
In v2.1.8 some parameters are missing documentation.
E.g.:
```+(void)subtractCurrencyFromWallet:(int)currencyId withAmount:(int)amount withReason:(NSString*)reason withLocation:(NSString*)location;```
is missing documentation on the location parameter. For me it's not obvious, what location means.

**Comment by FrankSpil** [comment]
Thank you for your feedback. Your right this was missing, it'll be available in the new release. The location is location where the event happened, for example in 'level1' or 'highscore_screen'. Most of the times this value is defined by our B.I. department and provided to the external developers. The parameter is optional and can be left empty: nil or @"".
