### ISSUE TITLE
Add Nullability specifiers

### ISSUE THREAD

**Issue by iCarambaa** [spilgames/spil-ios-sdk#8]
There are some new parameters for existing methods (location parameter for wallet, etc.). It would be nice to get Nullability specifiers, so I know which ones are required and which ones are not. At the moment I need to either treat them as breaking changes or walk through the code for every one of them and hope that I don't miss anything.

**Comment by FrankSpil** [comment]
Yes, makes sense to add them, they will be in the next release. Good feedback, thanks!
